  C THE FIRST PROGRAM I WROTE IN FORTRAN 77
  C WRITTEN ON A SUN MICROSYSTEMS BLADE 100 WORKSTATION
  C THE CODE ISN'T MUCH, BUT I SPENT MORE TIME DEBUGGING
  C IT THEN ANYTHING.... FUCKING FORTRAN
      PROGRAM MAIN
      IMPLICIT NONE
      WRITE (*,*) 'TRANS'
      WRITE (*,*) 'RIGHTS'
      STOP
      END
